### ISSUE TITLE
Disabled mod structure, causing the game to crash when creating a world.

### ISSUE THREAD

**Issue by Lymno** [ChoiceTheorem/Immersive-structures#1]
[latest.log](https://github.com/ChoiceTheorem/Immersive-structures/files/9290043/latest.log)
[crash-2022-08-09_21.24.41-client.txt](https://github.com/ChoiceTheorem/Immersive-structures/files/9290045/crash-2022-08-09_21.24.41-client.txt)
delete data/imst/worldgen/structures/el_dorado

**Comment by ChoiceTheorem** [comment]
change the delete files to data/imst/structures/el_dorado and see if it works

**Comment by ChoiceTheorem** [comment]
I might have told you to delete the wrong file so it causes the crash.

**Comment by Lymno** [comment]
> 

It worked！Structure coordinates can be located in-game, but there are actually no structures.
