### ISSUE TITLE
Add compatibility to Regions Unexplored mod

### ISSUE THREAD

**Issue by MbtMarco** [ChoiceTheorem/Immersive-structures#3]
https://modrinth.com/mod/regions-unexplored

**Comment by ChoiceTheorem** [comment]
Should be compatible as is.

**Comment by MbtMarco** [comment]
It should, however I have never found structures in the Regions Unexplorer
biomes.

Il Mer 9 Ago 2023, 10:50 ChoiceTheorem ***@***.***> ha
scritto:

**Comment by MbtMarco** [comment]
It should, however I have never found structures in the Regions Unexplorer biomes.

**Comment by MbtMarco** [comment]
Are they rare to find?

**Comment by ChoiceTheorem** [comment]
Can you bother to use /locate first?

**Comment by MbtMarco** [comment]
I have tried however each time I always find them in the vanilla biomes,
however I will try again, in case I show you with a screen recording I
can't find them in the custom biomes.

Il Mer 9 Ago 2023, 14:17 ChoiceTheorem ***@***.***> ha
scritto:
